name: Publish Extension
on:
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        if: env.VSCE_PAT != ''
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        working-directory: './extension code'
      - name: Skip Publish
        if: env.VSCE_PAT == ''
        run: echo "VSCE_PAT is not set. Skipping publication."
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        working-directory: './extension code'
